added CARNIVAL and readded LDGM
cbg-ethz/dce pull request #27
Opened 2021-07-20 11:19 UTC by MartinFXP

title +
some minor additions/edits (e.g., help files, package suggests)

2021-07-21 11:05 UTC, kpj requested changes
Looking snazzy!

2021-07-21 11:05 UTC, kpj commented on R/main.R
> +#' e.g., "meanp" or "sump". Alternatively, "vcovHC" can improve results
What would you think of properly validating our parameters with something like `match.arg`?

2021-07-21 11:05 UTC, kpj commented on inst/scripts/synthetic_benchmark/workflow/scripts/Carnival.R
> +# test <- carWrap(X,Y,G)
Is this commented out code needed or can it be removed?

2021-07-21 11:05 UTC, kpj commented on inst/scripts/synthetic_benchmark/workflow/scripts/DGE.R
> +# test2 <- dce(G,X,Y,solver = "lm")
Is this commented out needed?

2021-07-21 11:05 UTC, kpj commented on inst/scripts/synthetic_benchmark/workflow/scripts/LDGM.R
> +    system(paste0("matlab -batch \"Sigma1 = readmatrix('",mt.f,"'); Sigma2 = readmatrix('",wt.f,"'); lambda = 0.26924; cd('workflow/scripts/LDGM'); Theta = differential_graph(Sigma1,Sigma2,lambda); w
How is the value `0.26924` for lambda chosen?

2021-07-21 11:20 UTC, MartinFXP commented on inst/scripts/synthetic_benchmark/workflow/scripts/LDGM.R
> +    system(paste0("matlab -batch \"Sigma1 = readmatrix('",mt.f,"'); Sigma2 = readmatrix('",wt.f,"'); lambda = 0.26924; cd('workflow/scripts/LDGM'); Theta = differential_graph(Sigma1,Sigma2,lambda); w
From the package example. Added to the manuscript.

2021-07-21 11:22 UTC, MartinFXP commented on R/main.R
> +#' e.g., "meanp" or "sump". Alternatively, "vcovHC" can improve results
Probably a good idea.

2021-07-21 12:40 UTC, kpj commented on inst/scripts/synthetic_benchmark/workflow/scripts/LDGM.R
> +    system(paste0("matlab -batch \"Sigma1 = readmatrix('",mt.f,"'); Sigma2 = readmatrix('",wt.f,"'); lambda = 0.26924; cd('workflow/scripts/LDGM'); Theta = differential_graph(Sigma1,Sigma2,lambda); w
Makes sense!

2021-07-21 12:40 UTC, kpj commented on R/main.R
> +#' e.g., "meanp" or "sump". Alternatively, "vcovHC" can improve results
Great :D

2021-07-23 09:15 UTC, kpj requested changes

2021-07-23 09:15 UTC, kpj commented on R/main.R
> +    avail.tests <- c("lr","wald","vcovHC")
Please don't use periods in variable names.
Here you should use `avail_tests` instead.

More generally speaking, does it really improve readability to not simply define this list as an argument to `match.arg`?

2021-07-23 12:46 UTC, kpj requested changes

2021-07-23 12:46 UTC, kpj commented on R/main.R
> +    p_method <- match.arg(p_method, c("hmp", "meanp", "mean", "sum", "sump", "test"))
```
p_method <- match.arg(
    p_method,
    c("hmp", "meanp", "mean", "sum", "sump", "test")
)
```
;)

2021-07-23 12:49 UTC, kpj requested changes

2021-07-23 12:49 UTC, kpj commented on inst/scripts/synthetic_benchmark/workflow/scripts/DGE.R
> +  for (i in 1:nrow(edges)) {
`seq_len` should be used instead of `:`.

2021-07-23 13:32 UTC, kpj commented
Any idea why the test `(test-dce.R:219:3): different p-value computations work` is failing?
It's passing on master.

2021-07-23 13:45 UTC, MartinFXP commented
> Any idea why the test `(test-dce.R:219:3): different p-value computations work` is failing?
> It's passing on master.

The only change within the main part should be in the function `topologically_ordering()`. I don't see atm how that can influence the test.

2021-07-23 13:54 UTC, kpj commented
Shall I just merge this PR and see how it goes?

2021-07-23 13:58 UTC, MartinFXP commented
Let's do one more round. Maybe it was just a glitch.

2021-07-23 14:17 UTC, kpj commented
Seems like it didn't change 🤷

2021-07-23 14:20 UTC, MartinFXP commented
I know whats going on. I'll have another go in a sec.

2021-07-23 15:11 UTC, kpj commented
Nice! Good thing we have tests 😅
Should I merge it now?

2021-07-23 15:47 UTC, MartinFXP commented
Sure.

2021-07-23 20:42 UTC, merged