added GTEx validation
cbg-ethz/dce pull request #30
Opened 2021-08-22 23:53 UTC by dcevid

2021-08-23 09:23 UTC, kpj requested changes
Looks very good already, I added a few small comments :)

Please also mention this workflow in the `Project structure` section of the main `README.md`.

2021-08-23 09:23 UTC, kpj commented on inst/scripts/gtex_validation/workflow/scripts/prepare_all_datasets.R
> +library(rtracklayer)
Consider adding these additional dependencies (`rtracklayer`, `hash`) to the `Suggests` section of dce's DESCRIPTION to make the installation easier.

2021-08-23 09:23 UTC, kpj commented on inst/scripts/gtex_validation/workflow/Snakefile
> +		"processed_data/encodings.Rdata"
The output files of all rules should be stored in a folder called `results`.

2021-08-23 09:23 UTC, kpj commented on inst/scripts/gtex_validation/workflow/Snakefile
> +TISSUES = [str.split('.')[0] for str in os.listdir('raw_data/GTEx_Analysis_v8_eQTL_expression_matrices')]
Why is the `TISSUES` variable being defined here but then also overwritten later on?

2021-08-23 09:23 UTC, kpj commented on inst/scripts/gtex_validation/workflow/Snakefile
> +print('{num} valid tissues: '.format(num=len(valid_tissues)), valid_tissues)
It would be nice to have such setup code before all rule definitions

2021-08-23 09:23 UTC, kpj commented on inst/scripts/gtex_validation/workflow/scripts/explore_data.R
> +devtools::load_all("~/Documents/projects/CausalPathways/dce")
Same as before, absolute paths like this make it difficult to use for other people.

2021-08-25 09:48 UTC, dcevid commented on inst/scripts/gtex_validation/workflow/scripts/explore_data.R
> +devtools::load_all("~/Documents/projects/CausalPathways/dce")
those scripts are actually not in the snakemake workflow, but those are the ones that I ran locally manually.
I thought it could be useful for me to have it stored in github somewhere, I just could not find a better place for them.

2021-08-25 09:56 UTC, kpj commented on inst/scripts/gtex_validation/workflow/scripts/explore_data.R
> +devtools::load_all("~/Documents/projects/CausalPathways/dce")
I'd recommend putting all scripts which are useful for development but not actually used in the workflow into something like `resources/utils/`.

2021-08-25 10:57 UTC, dcevid commented on inst/scripts/gtex_validation/workflow/scripts/explore_data.R
> +devtools::load_all("~/Documents/projects/CausalPathways/dce")
I would not call this "useful for development", it is more that it is useful for my quick & dirty stuff :)

2021-08-25 11:36 UTC, kpj commented on inst/scripts/gtex_validation/workflow/scripts/explore_data.R
> +devtools::load_all("~/Documents/projects/CausalPathways/dce")
Sure, putting it into resources would be neat either way :D

2021-08-25 12:04 UTC, kpj commented on inst/scripts/gtex_validation/workflow/scripts/plot_dce.R
> +out = mget(load("/Users/cevidd/Desktop/dce/inst/scripts/gtex_validation/results/output/Breast_Mammary_Tissue#Lung.Rdata", envir=(NE. <- new.env())), envir=NE.)
This absolute path also leads to crashes

2021-08-25 12:21 UTC, dcevid commented on inst/scripts/gtex_validation/workflow/scripts/plot_dce.R
> +out = mget(load("/Users/cevidd/Desktop/dce/inst/scripts/gtex_validation/results/output/Breast_Mammary_Tissue#Lung.Rdata", envir=(NE. <- new.env())), envir=NE.)
oh, this was some debug stuff, the correct line is commented out

2021-09-14 10:02 UTC, merged